baseURL: https://ditlevs-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Ditlev Peter Meulengracht
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Jump into it! 
    subtitle: |-
      A Data Analytics Project at London Business School
    title: Ditlev's LBS Portfolio Website!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: LBS Street 2021
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ditlevm.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07463 477791
        title: Phone
  custom_css: []
  custom_js: []
  description: Test Description here
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ditlev's Company
    enable: yes
    quicklinks:
      - alt: Data Analytics at London Business School
        text: 'Course: '
        url: https://www.london.edu/masters-degrees/masters-in-financial-analysis/programme-content/core-courses
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/Ditlevm
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub Profile
        url: https://github.com/DitlevMeulengracht
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ditlevmeulengracht/
  image: ''
  name: Ditlev Peter Meulengracht
  navigation:
    button1:
#      - name: Get Started
#        url: blogs
    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: All sites
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Navigation
    subtitle: MFA2022 Data Analytics Website
    title: Ditlev's 
  tiles:
    enable: yes
    showcase:
      - image: LBS.jpeg
        subtitle: in pictures
        title: Experiences at LBS
        url: blogs/lbspictures
      - image: Resume1.jpeg
        subtitle: My Academic and Professional Experience
        title: Resume
        url: blogs/resume
      - image: Power.jpeg
        subtitle: An interactive map
        title: Power generating capacity
        url: blogs/power
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Check it out! 
    enable: yes
    subtitle: "Find More information here!"
    title: Additional Information
    url: blogs
